using System.ComponentModel;

namespace Engine.WeatherClasses
{
    public class CurrentConditions : BaseNotificationClass
    {
        //Data from the API is loaded into these classes (generated by https://json2csharp.com/) from the deserialized json. Variables are thusly named.
        //There is a possibility of getting null values for some data, so the variables are prepared for this. OnPropertyChanged method is not needed
        //here and will be cleaned up further on.
        private string? _datetime;
        private double? _temp;
        private double? _precip;
        private double? _windspeed;
        private double? _winddir;
        private string? _conditions;
        public string? datetime
        {
            get { return _datetime; }
            set
            {
                _datetime = value;
                OnPropertyChanged("datetime");
            }
        }
        public double? temp
        {
            get { return _temp; }
            set
            {
                _temp = value;
                OnPropertyChanged("temp");
            }
        }
        public double? precip
        {
            get { return _precip; }
            set
            {
                _precip = value;
                OnPropertyChanged("precip");
            }
        }
        public double? windspeed
        {
            get { return _windspeed; }
            set
            {
                _windspeed = value;
                OnPropertyChanged("windspeed");
            }
        }
        public double? winddir
        {
            get { return _winddir; }
            set
            {
                _winddir = value - 90;  //In order to orient the arrow correctly in the UI we need to adjust the value when it's set.
                OnPropertyChanged("windir");
            }
        }
        public string? conditions
        {
            get { return _conditions; }
            set
            {
                _conditions = value;
                OnPropertyChanged("conditions");
            }
        }

    }

    public class WeatherReport : BaseNotificationClass 
    {
        //Root class, we need this for the API data to load properly. PropertyChanged code will be cleaned up here as well.
        private string _address;
        private CurrentConditions _currentConditions;
        public string ComboBoxDisplay { get; set; } //Extra variable for displaying search results in the combo box.
        public string address
        {
            get { return _address; }
            set
            {
                _address = value;
            }
        }
        public CurrentConditions currentConditions
        {
            get { return _currentConditions; }
            set
            {
                _currentConditions = value;
            }
        }

        public WeatherReport()
        {
            currentConditions = new CurrentConditions();
        }

        public event PropertyChangedEventHandler? PropertyChanged;

        protected virtual void OnPropertyChanged(string propertyName)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }
    }
}
